language: android
jdk:
  - oraclejdk8

android:
    components:
        - tools
        - build-tools-26.0.1
        - android-24
    licences:
        - '.+'
script:
    - cd pulltorefresh
    - ./gradlew assembleDebug

