language: android
jdk:
  - oraclejdk8

android:
    components:
        - tools
        - build-tools-28.0.3
        - android-24
    licences:
        - '.+'
script:
    - cd pulltorefresh
    - ./gradlew assembleDebug

